### DISCUSSION TITLE
Sort by Recently Added

### DISCUSSION THREAD

**Discussion by S1gv4rd** [jeremehancock/Posteria#18] [Feature Requests]
Would love the ability to see new items first, as the rest of my library already has the right covers.

**Comment by jeremehancock** [comment]
Adding this from an Issue:

[sup3rmark](https://github.com/sup3rmark)
opened [19 hours ago](https://github.com/jeremehancock/Posteria/issues/17#issue-2921589169)
Good work on this so far! Would be great if there was an option to sort using the Sort Titles we can set in Plex. Personally, I often update Sort Titles on movies that are part of a series so that they group together in the full list, so this would help ensure I'm getting similar posters across movies in a series without scrolling back and forth to view them all.

Thanks!

**Comment by jeremehancock** [comment]
@S1gv4rd @sup3rmark

I am going to get started on this next.

I don't really want to add much more to the UI so I was thinking about just adding a Docker Env Var to set this so the user can choose how things are sorted. Seems like most people would want either Title or Sort Title. I will probably put it to default to Sort Title since that would make sense to me.

Sound good to ya'll?

Thanks

**Reply by S1gv4rd** [reply]
Sounds great to me. Looking forward to it and keep up the good work!

**Comment by jeremehancock** [comment]
@S1gv4rd @sup3rmark

I have got this working!

I would love to get one or both of ya'll to test this out before I release.

To test update to this `docker-compose.yml` 

```
services:
  posteria:
    image: bozodev/posteria:date-sort
    container_name: posteria
    ports:
      - "1818:80"
    environment:
      - SITE_TITLE=Posteria
      - AUTH_USERNAME=admin # Change this!
      - AUTH_PASSWORD=changeme # Change this!
      - SESSION_DURATION=3600 # In seconds
      - IMAGES_PER_PAGE=24
      - MAX_FILE_SIZE=5242880 # In bytes

      - PLEX_SERVER_URL=
      - PLEX_TOKEN=
      - PLEX_REMOVE_OVERLAY_LABEL=true # Set to true for Kometa compatibility

      - IGNORE_ARTICLES_IN_SORT=true # Set to false to sort with articles (A, An, The) included
      - SORT_BY_DATE_ADDED=true # Set to false to sort Alphabetically instead of by Recently Added date in Plex

      - AUTO_IMPORT_ENABLED=true # Enable/disable auto-import
      - AUTO_IMPORT_SCHEDULE=1h # Schedule 24h, 12h, 6h, 3h, 1h
      - AUTO_IMPORT_MOVIES=true # Import Movie posters
      - AUTO_IMPORT_SHOWS=true # Import TV Show posters
      - AUTO_IMPORT_SEASONS=true # Import TV season posters
      - AUTO_IMPORT_COLLECTIONS=true # Import Collection posters
    volumes:
      - ./posters/movies:/var/www/html/posters/movies
      - ./posters/tv-shows:/var/www/html/posters/tv-shows
      - ./posters/tv-seasons:/var/www/html/posters/tv-seasons
      - ./posters/collections:/var/www/html/posters/collections
      - ./data:/var/www/html/data # Logs are found here
    restart: unless-stopped
```

This should allow the `Auto Import` to update the files to the correct filenames for the sorting. If you do manual imports from the UI then you will get Orphaned files that you can delete in the UI. If you see any weirdness or duplicates I recommend using the Reset option and doing a fresh import. You shouldn't have to do that, but that is why I added the Reset option.

Please let me know if you have any issues or hopefully if it all works. 

Thanks!!!
