### ISSUE TITLE
Enhancement Request - Remove "Overlay" label when updating poster

### ISSUE THREAD

**Issue by dlhall111** [jeremehancock/Posteria#7]
First of all, great project!  I like to tweak my posters frequently and this seems like it will make that experience a lot easier, not to mention having a pseudo-backup of posters just in case.

But I have a request, I imagine many of us who might use this are also using Kometa and if you update a poster in Plex without removing the "Overlay" label the poster won't get updated by Kometa on the next run.  Would it be possible to add some additional logic (optionally I suppose) to remove the "Overlay" label from the item being updated via Posteria?  Otherwise it's a manual step, which is not that big of a deal but would be awesome if it could be included in the change via the poster update.

Thanks!

**Comment by jeremehancock** [comment]
Thank you very much! I am glad you like the project!!

I am familiar with Kometa in concept, but I have never used it. So I will need a bit more info. Are you asking if Posteria can remove a label via the Plex API?

If I am understanding correctly I lean towards not wanting to make changes that are not necessary for Posteria's functions. However, I don't fully understand the implications of not doing what you are ask much less the implications of doing it.

If you can provide me more details and context I will definitely consider it.

**Comment by dlhall111** [comment]
Absolutely.  Here's the link to the Kometa docs specific to what I'm referring to here:  https://metamanager.wiki/en/latest/files/overlays/#overlay-understandings.  In particular, this section in the linked page:
![Image](https://github.com/user-attachments/assets/42b1383f-87ed-4f1f-87bf-c0b3ddc30398)

One popular use for Kometa is applying overlays on the posters where you add pieces of information that can get updated on each run potentially, for example:
![Image](https://github.com/user-attachments/assets/6f54ed82-0989-4ed0-928c-895dbb6c6749)

If I change this poster via Posteria, the "Overlay" label remains in Plex:
![Image](https://github.com/user-attachments/assets/c526ad21-e88d-4c46-84d2-1e5ceedcea3b)

Which means the poster wouldn't get updated on the next Kometa run (unless something else has changed like the rating or if I changed to another file encode that had a different resolution or HDR profile)... so it would be the new poster from Posteria but without the overlays.  To trigger the new poster to get the overlays re-applied you have to remove the "Overlay" label per the linked Kometa doc.  Meaning my current process for updating posters in Plex is to change the poster then remove the "Overlay" label to ensure the next Kometa run re-applies the overlays.

I'm sure many users wouldn't care at all about this but those that might host such a handy poster-management application might also be hosting Kometa so I figured it was worth proposing as an optional configuration enhancement.  Let me know if you'd like any other info, thanks!

**Comment by jeremehancock** [comment]
Thank you for the additional info. 

So you are basically asking this:

When a poster is updated in Posteria the Overlay Label on the same media entry should be removed.

If I do that does that mean the next Kometa run will put the overlay back on the new poster that was updated in Posteria?

I need to be sure I fully understand since this will mean Posteria is making changes that are somewhat outside of Posteria's concern. I agree that I want Posteria to play well with Kometa. I just don't want to mess anything up for Kometa users either.

**Comment by dlhall111** [comment]
Yes, you've got it right.  And I completely understand your concerns about how this might impact Kometa or anything else, so if this could be an environment config option (or configurable in some other manner) then it would be on the user to decide if they want this change to be made or not when updating a poster in Plex via Posteria.  Many thanks for considering!

**Comment by jeremehancock** [comment]
Thank you for the confirmation.

I agree that allowing user to configure Posteria to remove the labels seems reasonable. 

I have spent some time tonight trying to get the Plex API to remove the label and so far I haven't been able to get it to work. I will keep this on my list of things to work on for sure. Just need to figure out. :)

I will leave this open to help me track it.

Thanks again.

**Comment by jeremehancock** [comment]
@dlhall111 

Great news!!

I have it working. I would like you to test it if you don't mind to be sure that it is doing what you intend.

I have updated Posteria with a Docker Compose env var to remove the Overlay label from the media item if the poster is changed from Posteria. It will only remove it if the poster actually changes.

To test this you can just update your `docker-compose.yml` file to this one.

```
services:
  posteria:
    image: bozodev/posteria:kometa
    container_name: posteria
    ports:
      - "1818:80"
    environment:
      - SITE_TITLE=Posteria
      - AUTH_USERNAME=admin
      - AUTH_PASSWORD=changme
      - SESSION_DURATION=86400
      - IMAGES_PER_PAGE=24
      - MAX_FILE_SIZE=3600
      - PLEX_SERVER_URL=
      - PLEX_TOKEN=
      - PLEX_REMOVE_OVERLAY_LABEL=true
    volumes:
      - ./posters/movies:/var/www/html/posters/movies
      - ./posters/tv-shows:/var/www/html/posters/tv-shows
      - ./posters/tv-seasons:/var/www/html/posters/tv-seasons
      - ./posters/collections:/var/www/html/posters/collections
    restart: unless-stopped
```
I did notice in testing that if I checked the Plex Web UI quickly after changing the poster it might not show it gone yet. It takes a few extra seconds.

If you could try this out and be sure that removing the label does fix the "work flow" issues that you would have with Posteria and Kometa I would really appreciate it.

Thanks!
